// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynaxmggvbjnxdglbfmfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluYXhtZ2d2YmpueGRnbGJmbWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NzUyNzUsImV4cCI6MjA1NDI1MTI3NX0.8_QzhXf3SDtN_7xHfjflFz4V0Zz-G0AqS2HdnlqYhKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);